# Generated by Django 2.2.5 on 2021-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210716_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='geneder',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('krw', 'KRW')], max_length=2, null=True),
        ),
    ]
