# Generated by Django 2.2.5 on 2021-07-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210718_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomtype',
            new_name='room_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomType'),
        ),
    ]
