# Generated by Django 2.2.5 on 2021-07-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20210718_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenity',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomType'),
        ),
    ]
