# Generated by Django 2.2.5 on 2021-08-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedday',
            old_name='reservatiom',
            new_name='reservation',
        ),
    ]
